/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "nvr.h"

#define pwdLEN 256


bool_t
xdr_LOGINargs(XDR * xdrs, LOGINargs * objp)
{
	register int32_t *buf;

	if (!xdr_string(xdrs, &objp->ip, CMN_LEN))
		return FALSE;
	if (!xdr_int(xdrs, &objp->port))
		return FALSE;
	if (!xdr_string(xdrs, &objp->userName, CMN_LEN))
		return FALSE;
	if (!xdr_string(xdrs, &objp->pwd, CMN_LEN))
		return FALSE;
	return TRUE;
}

bool_t
xdr_CMMNargs(XDR * xdrs, CMMNargs * objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_u_int(xdrs, &objp->loginID))
			return FALSE;
		if (!xdr_string(xdrs, &objp->camerID, camerIDLEN))
			return FALSE;
		buf = XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->recordType))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->beginTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->endTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->mode))
				return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->recordType);
			IXDR_PUT_U_LONG(buf, objp->beginTime);
			IXDR_PUT_U_LONG(buf, objp->endTime);
			IXDR_PUT_U_LONG(buf, objp->mode);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_u_int(xdrs, &objp->loginID))
			return FALSE;
		if (!xdr_string(xdrs, &objp->camerID, camerIDLEN))
			return FALSE;
		buf = XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->recordType))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->beginTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->endTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->mode))
				return FALSE;
		} else {
			objp->recordType = IXDR_GET_LONG(buf);
			objp->beginTime = IXDR_GET_U_LONG(buf);
			objp->endTime = IXDR_GET_U_LONG(buf);
			objp->mode = IXDR_GET_U_LONG(buf);
		}
		return TRUE;
	}

	if (!xdr_u_int(xdrs, &objp->loginID))
		return FALSE;
	if (!xdr_string(xdrs, &objp->camerID, camerIDLEN))
		return FALSE;
	if (!xdr_int(xdrs, &objp->recordType))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->beginTime))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->endTime))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->mode))
		return FALSE;
	return TRUE;
}

bool_t
xdr_READargs(XDR * xdrs, READargs * objp)
{
	register int32_t *buf;

	if (!xdr_u_int(xdrs, &objp->playHandle))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->readSize))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->mode))
		return FALSE;
	return TRUE;
}

bool_t
xdr_SEARCHargs(XDR * xdrs, SEARCHargs * objp)
{
	register int32_t *buf;

	if (!xdr_CMMNargs(xdrs, objp))
		return FALSE;
	return TRUE;
}

bool_t
xdr_READres(XDR * xdrs, READres * objp)
{
	register int32_t *buf;

	if (!xdr_u_int(xdrs, &objp->dataLen))
		return FALSE;
	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, ~0))
		return FALSE;
	return TRUE;
}

bool_t
xdr_HEADERinfo(XDR * xdrs, HEADERinfo * objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, HEAD_LEN))
			return FALSE;
		buf = XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->beginTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->endTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->nextBeginTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->recordSize))
				return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->beginTime);
			IXDR_PUT_U_LONG(buf, objp->endTime);
			IXDR_PUT_U_LONG(buf, objp->nextBeginTime);
			IXDR_PUT_U_LONG(buf, objp->recordSize);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, HEAD_LEN))
			return FALSE;
		buf = XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->beginTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->endTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->nextBeginTime))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->recordSize))
				return FALSE;
		} else {
			objp->beginTime = IXDR_GET_U_LONG(buf);
			objp->endTime = IXDR_GET_U_LONG(buf);
			objp->nextBeginTime = IXDR_GET_U_LONG(buf);
			objp->recordSize = IXDR_GET_U_LONG(buf);
		}
		return TRUE;
	}

	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, HEAD_LEN))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->beginTime))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->endTime))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->nextBeginTime))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->recordSize))
		return FALSE;
	return TRUE;
}

bool_t
xdr_SEARCHres(XDR * xdrs, SEARCHres * objp)
{
	register int32_t *buf;

	if (!xdr_CMMNargs(xdrs, &objp->cmmnArgs))
		return FALSE;
	if (!xdr_string(xdrs, &objp->describe, describeLEN))
		return FALSE;
	if (!xdr_int(xdrs, &objp->describeLen))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->nextBeginTime))
		return FALSE;
	return TRUE;
}

bool_t
xdr_CREATEargs(XDR * xdrs, CREATEargs * objp)
{
	register int32_t *buf;

	if (!xdr_u_int(xdrs, &objp->loginID))
		return FALSE;
	if (!xdr_string(xdrs, &objp->camerID, camerIDLEN))
		return FALSE;
	if (!xdr_string(xdrs, &objp->camerAlias, camerIDLEN))
		return FALSE;
	if (!xdr_int(xdrs, &objp->recordType))
		return FALSE;
	if (!xdr_bytes(xdrs, (char **)&objp->header.header_val, (u_int *) & objp->header.header_len, HEAD_LEN))
		return FALSE;
	if (!xdr_string(xdrs, &objp->describe, describeLEN))
		return FALSE;
	if (!xdr_int(xdrs, &objp->describeLen))
		return FALSE;
	return TRUE;
}

bool_t
xdr_WRITEargs(XDR * xdrs, WRITEargs * objp)
{
	register int32_t *buf;

	if (!xdr_u_int(xdrs, &objp->recordHandle))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->beginTime))
		return FALSE;
	if (!xdr_bytes(xdrs, (char **)&objp->data.data_val, (u_int *) & objp->data.data_len, ~0))
		return FALSE;
	return TRUE;
}

bool_t
xdr_DELargs(XDR * xdrs, DELargs * objp)
{
	register int32_t *buf;

	if (!xdr_CMMNargs(xdrs, objp))
		return FALSE;
	return TRUE;
}

bool_t
xdr_VOLUMinfo(XDR * xdrs, VOLUMinfo * objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE(xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->volSizeHigh))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->volSizeLow))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->usedSizeHigh))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->usedSizeLow))
				return FALSE;
			if (!xdr_int(xdrs, &objp->savedDays))
				return FALSE;
			if (!xdr_int(xdrs, &objp->delPolicy))
				return FALSE;
			if (!xdr_int(xdrs, &objp->encoderType))
				return FALSE;
			if (!xdr_int(xdrs, &objp->resolusion))
				return FALSE;
			if (!xdr_int(xdrs, &objp->datarate))
				return FALSE;
		} else {
			IXDR_PUT_U_LONG(buf, objp->volSizeHigh);
			IXDR_PUT_U_LONG(buf, objp->volSizeLow);
			IXDR_PUT_U_LONG(buf, objp->usedSizeHigh);
			IXDR_PUT_U_LONG(buf, objp->usedSizeLow);
			IXDR_PUT_LONG(buf, objp->savedDays);
			IXDR_PUT_LONG(buf, objp->delPolicy);
			IXDR_PUT_LONG(buf, objp->encoderType);
			IXDR_PUT_LONG(buf, objp->resolusion);
			IXDR_PUT_LONG(buf, objp->datarate);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE(xdrs, 9 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->volSizeHigh))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->volSizeLow))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->usedSizeHigh))
				return FALSE;
			if (!xdr_u_int(xdrs, &objp->usedSizeLow))
				return FALSE;
			if (!xdr_int(xdrs, &objp->savedDays))
				return FALSE;
			if (!xdr_int(xdrs, &objp->delPolicy))
				return FALSE;
			if (!xdr_int(xdrs, &objp->encoderType))
				return FALSE;
			if (!xdr_int(xdrs, &objp->resolusion))
				return FALSE;
			if (!xdr_int(xdrs, &objp->datarate))
				return FALSE;
		} else {
			objp->volSizeHigh = IXDR_GET_U_LONG(buf);
			objp->volSizeLow = IXDR_GET_U_LONG(buf);
			objp->usedSizeHigh = IXDR_GET_U_LONG(buf);
			objp->usedSizeLow = IXDR_GET_U_LONG(buf);
			objp->savedDays = IXDR_GET_LONG(buf);
			objp->delPolicy = IXDR_GET_LONG(buf);
			objp->encoderType = IXDR_GET_LONG(buf);
			objp->resolusion = IXDR_GET_LONG(buf);
			objp->datarate = IXDR_GET_LONG(buf);
		}
		return TRUE;
	}

	if (!xdr_u_int(xdrs, &objp->volSizeHigh))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->volSizeLow))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->usedSizeHigh))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->usedSizeLow))
		return FALSE;
	if (!xdr_int(xdrs, &objp->savedDays))
		return FALSE;
	if (!xdr_int(xdrs, &objp->delPolicy))
		return FALSE;
	if (!xdr_int(xdrs, &objp->encoderType))
		return FALSE;
	if (!xdr_int(xdrs, &objp->resolusion))
		return FALSE;
	if (!xdr_int(xdrs, &objp->datarate))
		return FALSE;
	return TRUE;
}

bool_t
xdr_SETRECINFOargs(XDR * xdrs, SETRECINFOargs * objp)
{
	register int32_t *buf;

	if (!xdr_SEARCHres(xdrs, objp))
		return FALSE;
	return TRUE;
}

bool_t
xdr_GETRECSIZEargs(XDR * xdrs, GETRECSIZEargs * objp)
{
	register int32_t *buf;

	if (!xdr_string(xdrs, &objp->camerID, camerIDLEN))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->beginTime))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->endTime))
		return FALSE;
	return TRUE;
}

bool_t
xdr_CREATRECVOLargs(XDR * xdrs, CREATRECVOLargs * objp)
{
	register int32_t *buf;

	if (!xdr_string(xdrs, &objp->volumeid, ~0))
		return FALSE;
	if (!xdr_string(xdrs, &objp->name, ~0))
		return FALSE;
	if (!xdr_string(xdrs, &objp->alias, ~0))
		return FALSE;
	if (!xdr_short(xdrs, &objp->savedDays))
		return FALSE;
	if (!xdr_char(xdrs, &objp->delPolicy))
		return FALSE;
	if (!xdr_char(xdrs, &objp->encodeType))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->blocks))
		return FALSE;
	if (!xdr_u_int(xdrs, &objp->blockSize))
		return FALSE;
	return TRUE;
}

bool_t
xdr_DELRECVOLargs(XDR * xdrs, DELRECVOLargs * objp)
{
	register int32_t *buf;

	if (!xdr_string(xdrs, &objp->cameraID, ~0))
		return FALSE;
	if (!xdr_int(xdrs, &objp->mode))
		return FALSE;
	return TRUE;
}

bool_t
xdr_RECORDBYORDERargs (XDR *xdrs, RECORDBYORDERargs *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_string(xdrs, &objp->camerID, camerIDLEN))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->beginTime))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->endTime))
		 return FALSE;
	return TRUE;
}


bool_t
xdr_RECORDBYORDERres (XDR *xdrs, RECORDBYORDERres *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->flag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->beginTime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->endTime))
				 return FALSE;

		} else {
		IXDR_PUT_U_LONG(buf, objp->flag);
		IXDR_PUT_U_LONG(buf, objp->beginTime);
		IXDR_PUT_U_LONG(buf, objp->endTime);
		}
		 if (!xdr_string(xdrs, &objp->describe, describeLEN))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->describeLen))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_u_int (xdrs, &objp->flag))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->beginTime))
				 return FALSE;
			 if (!xdr_u_int (xdrs, &objp->endTime))
				 return FALSE;

		} else {
		objp->flag = IXDR_GET_U_LONG(buf);
		objp->beginTime = IXDR_GET_U_LONG(buf);
		objp->endTime = IXDR_GET_U_LONG(buf);
		}
		 if (!xdr_string(xdrs, &objp->describe, describeLEN))
			 return FALSE;
		 if (!xdr_int (xdrs, &objp->describeLen))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_u_int (xdrs, &objp->flag))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->beginTime))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->endTime))
		 return FALSE;
     if (!xdr_string(xdrs, &objp->describe, describeLEN)) 
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->describeLen))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_DELVEDVOLargs(XDR * xdrs, DELVEDVOLargs * objp)
{
	register int32_t *buf;

	if (!xdr_string(xdrs, &objp->volname, ~0))
		return FALSE;
	if (!xdr_int(xdrs, &objp->mode))
		return FALSE;    
	return TRUE;
}

